apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: club-rep
  name: club_rep
spec:
  ports:
    - name: "3311"
      port: 3311
      targetPort: 3306
  selector:
    io.kompose.service: club-rep
