apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: employee-rep
  name: employee_rep
spec:
  ports:
    - name: "3309"
      port: 3309
      targetPort: 3306
  selector:
    io.kompose.service: employee-rep
