apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/asid-my-db-network: "true"
        io.kompose.service: eureka-server
    spec:
      containers:
        - image: eurekaserver:latest
          name: eureka-server
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
      restartPolicy: Always
