apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: view-rep
  name: view_rep
spec:
  ports:
    - name: "3312"
      port: 3312
      targetPort: 3306
  selector:
    io.kompose.service: view-rep
